# Test against this version of Node.js
environment:
  matrix:
    - nodejs_version: 4.0.0

# Install scripts. (runs after repo cloning)
install:
  - cinst firefox
  - cinst googlechrome
  - cinst javaruntime
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - cmd: npm test

# Don't actually build.
build: off
